service: import-service
frameworkVersion: '3'

custom:
  queueName: catalogItemsQueue

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  environment:
    user: ${file(../../db-config.json):user}
    password: ${file(../../db-config.json):password}
    database: ${file(../../db-config.json):database}
    host: ${file(../../db-config.json):host}  
    port: ${file(../../db-config.json):port}
    REGION: "eu-central-1"

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::csv-products-unstoo/*"
        - "arn:aws:s3:::csv-products-unstoo"
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource:
        Fn::GetAtt: [ CatalogQueue, Arn ]

functions:
  importProductsFile:
    handler: index.importProductsFile
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                  name: true
  importFileParser:
    handler: index.importFileParser
    environment:
      SQS_URL:
        Ref: CatalogQueue
    events:
      - s3:
          bucket: csv-products-unstoo
          event: s3:ObjectCreated:*
          rules: 
            - prefix: uploaded/
            - suffix: .csv
          existing: true
  catalogBatchProcess:
    handler: index.catalogBatchProcess
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ CatalogQueue, Arn ]
          batchSize: 5

resources:
  Resources:
    CatalogQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.queueName}