service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::import-service-dev-serverlessdeploymentbucket-rthzbbah9s7a"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::import-service-dev-serverlessdeploymentbucket-rthzbbah9s7a/*"

functions:
  importProductsFile:
    handler: index.importProductsFile
    events:
      - http:
          path: /import
          method: get
          integration: lambda-proxy
          request:
            parameters:
              querystrings:
                name: true

