service: import-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  # s3:
  #   # Eventual additional properties in camel case
  #   importFileBucket:
  #     # Supported properties are the same ones as supported by CF resource for S3 bucket
  #     # See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  #     name: unstoo-import-file-bucket
  # # httpApi:
  # #   cors: true 

# plugins:
#   - serverless-auto-swagger

functions:
  importProductsFile:
    handler: index.importProductsFile
    events:
      - http:
          path: /import
          method: get
          integration: lambda-proxy
          request:
            parameters:
              querystrings:
                name: true

